### ISSUE TITLE
No sound with kernel 6.0

### ISSUE THREAD

**Issue by DigiAngel** [egorenar/snd-hda-codec-cs8409#7]
Sadly I no longer have sound with kernel 6.0.  Any fix for this?  Thank you.

**Comment by egorenar** [comment]
master branch should work, i'm on 6.5 kernel.

**Comment by DigiAngel** [comment]
First off thank you SO much for making this...it made this 2019 Retina 4K iMac useful :)  In gathering the information to send to you I discovered that the module wasn't loaded.  After recompiling and reinstalling....worked fine :100: Macs...go figure ;)  I'll open up a second help in a second for a longstanding issue I've had...thanks again!!
